### ISSUE TITLE
text of mail for institution should be generated

### ISSUE THREAD

**Issue by mmmaly** [martinmacko47/chcemvediet#19]
* should include the user details
* should include some fixed text (greeting, legal text, etc.)
* should include what the user put into the text box

**Comment by mmmaly** [comment]
Subject: Ziadost o informacie podla 211/2000 Z.z.:  (subject from request subject box)

Pre: (institution name, adress, email)
Od: (user name, postal address, email)

Dobrý deň,
na základe zákona č. 211/2000 Z. z. o slobodnom prístupe k informáciám
v znení neskorších predpisov žiadam o nasledovné informácie:

 (what user put into the textbox)


Informáciu žiadam zaslať v elektronickej podobe na moju emailovú
adresu (user email) .

V zmysle § 14 ods 5. zákona žiadam o potvrdenie prijatia žiadosti o informácie.

Ďakujem,
(user name)

**Comment by martinmacko47** [comment]
I think we should discuss the letter form in more details a little bit.

**Comment by martinmacko47** [comment]
The "Pre:"/"Od:" lines are hidden in the form because there are already applicant/obligee fields above them. They are shown only in final emails.

Templates for subject and content fields:
 - [chcemvediet/apps/inforequests/templates/inforequests/forms/create-subject.txt](/martinmacko47/chcemvediet/blob/master/chcemvediet/apps/inforequests/templates/inforequests/forms/create-subject.txt)
 - [chcemvediet/apps/inforequests/templates/inforequests/forms/create-content.txt](/martinmacko47/chcemvediet/blob/master/chcemvediet/apps/inforequests/templates/inforequests/forms/create-content.txt)

Tooltip for unique email in content field:
 - chcemvediet/apps/inforequests/templates/inforequests/tooltips/create-content-unique-email.{[en](/martinmacko47/chcemvediet/blob/master/chcemvediet/apps/inforequests/templates/inforequests/tooltips/create-content-unique-email.en.txt),[sk](/martinmacko47/chcemvediet/blob/master/chcemvediet/apps/inforequests/templates/inforequests/tooltips/create-content-unique-email.sk.txt)}.txt

Changed meaning of .po ([sk](/martinmacko47/chcemvediet/blob/master/chcemvediet/locale/sk/LC_MESSAGES/django.po), [en](/martinmacko47/chcemvediet/blob/master/chcemvediet/locale/en/LC_MESSAGES/django.po)) msgid for subject and content fields placeholders:
 - ``inforequests:InforequestForm:subject:placeholder``
 - ``inforequests:InforequestForm:content:placeholder``

**Comment by mmmaly** [comment]
it works.
